# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          OOPP_DB_NAME: ''
          OOPP_DB_HOST: '127.0.0.1'
          OOPP_DB_USERID: 'root'
          OOPP_DB_PASSWORD: ''
      - image: circleci/mysql:5.7-ram
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-py3.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-py3.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-py3.txt" }}

      - run:
          name: wait for db
          command: 'dockerize -wait tcp://127.0.0.1:3306 -timeout 120s'
      
      - run:
          name: run tests
          command: |
            mkdir -p ./oopp_testresult
            mkdir -p ./oopp_testhtml
            . venv/bin/activate
            python manage.py test --settings oOPp.settings_test

      - store_test_results:
          path: ./oopp_testresult
      
      - store_artifacts:
          path: ./oopp_testresult


workflows:
  version: 2
  workflow:
    jobs:
      - build