# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  shared-executor:
    docker:
      - image: circleci/python:3.7
        environment:
          OOPP_DB_NAME: ''
          OOPP_DB_HOST: '127.0.0.1'
          OOPP_DB_USERID: 'root'
          OOPP_DB_PASSWORD: ''
      - image: circleci/mysql:5.7

    working_directory: ~/repo


jobs:
  build:
    executor: shared-executor
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-py3.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-py3.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-py3.txt" }}

      - run:
          name: wait for db
          command: 'dockerize -wait tcp://127.0.0.1:3306 -timeout 120s'
  test:
    executor: shared-executor
    steps:
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test --settings oOPp.settings_test

      - store_artifacts:
          path: test-reports
          destination: test-reports


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test