# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsettings',
            name='responseType',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
