# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0003_auto_20180725_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OPConfigratuins',
            new_name='OPConfigrations',
        ),
    ]
