# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0004_auto_20180725_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opsettings',
            old_name='scope',
            new_name='scopes',
        ),
    ]
