# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0005_auto_20180726_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OPTokens',
        ),
        migrations.RenameField(
            model_name='opsettings',
            old_name='scopes',
            new_name='scope',
        ),
        migrations.AddField(
            model_name='opconfigrations',
            name='jwkSet',
            field=models.TextField(blank=True),
        ),
    ]
