# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0006_auto_20180801_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsettings',
            name='revocationEndpoint',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
