# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0007_opsettings_revocationendpoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OPConfigrations',
            new_name='OPConfigurations',
        ),
        migrations.RenameField(
            model_name='opconfigurations',
            old_name='configrations',
            new_name='configurations',
        ),
        migrations.AlterModelTable(
            name='opconfigurations',
            table='opconfigurations',
        ),
    ]
